name: Integration tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            setup.py
            test-requirements.txt
      - name: Install Python dependencies
        run: |
          pip install -r test-requirements.txt
          pip install .
      - name: Install RisingWave
        run: curl -L https://raw.githubusercontent.com/risingwavelabs/risingwave/refs/heads/main/scripts/install/install-risingwave.sh | sh
      - name: Run integration tests
        run: |
          ./risingwave >/dev/null 2>stderr.log &
          while :; do
            ready=$(grep -c "ready" stderr.log)
            echo "!!!!!! ready: $ready"
            [[ $ready -gt 0 ]] && break
            sleep 1
          done
          echo "!!!!!!!!!!!!!!!!"
          pytest
